/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appPlayRouteImport } from './routes/(app)/play'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/auth/forgot-password'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth/login'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/auth/reset-password'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth/signup'
import { Route as authAuthVerifyEmailRouteImport } from './routes/(auth)/auth/verify-email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appPlayRoute = appPlayRouteImport.update({
  id: '/(app)/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/(auth)/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/(auth)/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/(auth)/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthVerifyEmailRoute = authAuthVerifyEmailRouteImport.update({
  id: '/(auth)/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/play': typeof appPlayRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/reset-password': typeof authAuthResetPasswordRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/auth/verify-email': typeof authAuthVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/play': typeof appPlayRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/reset-password': typeof authAuthResetPasswordRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/auth/verify-email': typeof authAuthVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/play': typeof appPlayRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/reset-password': typeof authAuthResetPasswordRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/(auth)/auth/verify-email': typeof authAuthVerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/play'
    | '/profile'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/play'
    | '/profile'
    | '/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
  id:
    | '__root__'
    | '/'
    | '/(app)/dashboard'
    | '/(app)/play'
    | '/(app)/profile'
    | '/(app)/settings'
    | '/(auth)/auth/forgot-password'
    | '/(auth)/auth/login'
    | '/(auth)/auth/reset-password'
    | '/(auth)/auth/signup'
    | '/(auth)/auth/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appDashboardRoute: typeof appDashboardRoute
  appPlayRoute: typeof appPlayRoute
  appProfileRoute: typeof appProfileRoute
  appSettingsRoute: typeof appSettingsRoute
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
  authAuthVerifyEmailRoute: typeof authAuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/play': {
      id: '/(app)/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof appPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/forgot-password': {
      id: '/(auth)/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/reset-password': {
      id: '/(auth)/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/verify-email': {
      id: '/(auth)/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof authAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appDashboardRoute: appDashboardRoute,
  appPlayRoute: appPlayRoute,
  appProfileRoute: appProfileRoute,
  appSettingsRoute: appSettingsRoute,
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
  authAuthSignupRoute: authAuthSignupRoute,
  authAuthVerifyEmailRoute: authAuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
